// Curated large-cap US universe for the US Markets page. Not "all" US
// stocks -- a real, useful set (NASDAQ-100 / S&P mega-caps) that stays
// within Yahoo's batch quote limits and renders as a real dashboard
// rather than an unusable wall of tickers.
export const US_STOCKS = [
    { symbol: "AAPL", name: "Apple Inc." },
    { symbol: "MSFT", name: "Microsoft Corporation" },
    { symbol: "NVDA", name: "NVIDIA Corporation" },
    { symbol: "GOOGL", name: "Alphabet Inc." },
    { symbol: "AMZN", name: "Amazon.com Inc." },
    { symbol: "META", name: "Meta Platforms Inc." },
    { symbol: "TSLA", name: "Tesla Inc." },
    { symbol: "AVGO", name: "Broadcom Inc." },
    { symbol: "NFLX", name: "Netflix Inc." },
    { symbol: "COST", name: "Costco Wholesale Corporation" },
    { symbol: "AMD", name: "Advanced Micro Devices Inc." },
    { symbol: "ADBE", name: "Adobe Inc." },
    { symbol: "PEP", name: "PepsiCo Inc." },
    { symbol: "CSCO", name: "Cisco Systems Inc." },
    { symbol: "INTC", name: "Intel Corporation" },
    { symbol: "CMCSA", name: "Comcast Corporation" },
    { symbol: "QCOM", name: "Qualcomm Inc." },
    { symbol: "TXN", name: "Texas Instruments Inc." },
    { symbol: "AMGN", name: "Amgen Inc." },
    { symbol: "INTU", name: "Intuit Inc." },
    { symbol: "HON", name: "Honeywell International Inc." },
    { symbol: "SBUX", name: "Starbucks Corporation" },
    { symbol: "BKNG", name: "Booking Holdings Inc." },
    { symbol: "ISRG", name: "Intuitive Surgical Inc." },
    { symbol: "GILD", name: "Gilead Sciences Inc." },
    { symbol: "ADP", name: "Automatic Data Processing Inc." },
    { symbol: "PANW", name: "Palo Alto Networks Inc." },
    { symbol: "MDLZ", name: "Mondelez International Inc." },
    { symbol: "ADI", name: "Analog Devices Inc." },
    { symbol: "PYPL", name: "PayPal Holdings Inc." },
    { symbol: "REGN", name: "Regeneron Pharmaceuticals Inc." },
    { symbol: "VRTX", name: "Vertex Pharmaceuticals Inc." },
    { symbol: "MU", name: "Micron Technology Inc." },
    { symbol: "LRCX", name: "Lam Research Corporation" },
    { symbol: "KLAC", name: "KLA Corporation" },
    { symbol: "CRWD", name: "CrowdStrike Holdings Inc." },
    { symbol: "SNPS", name: "Synopsys Inc." },
    { symbol: "CDNS", name: "Cadence Design Systems Inc." },
    { symbol: "MAR", name: "Marriott International Inc." },
    { symbol: "ORLY", name: "O'Reilly Automotive Inc." },
    { symbol: "PLTR", name: "Palantir Technologies Inc." },
];

export const US_STOCK_MAP = new Map(US_STOCKS.map((s) => [s.symbol, s]));
