const STOCKS = [
    { symbol: "RELIANCE",   yahooSymbol: "RELIANCE.NS",   name: "Reliance Industries",      sector: "Energy",    sectorIndex: "^CNXENERGY"  },
    { symbol: "TCS",        yahooSymbol: "TCS.NS",        name: "Tata Consultancy Services", sector: "IT",        sectorIndex: "^CNXIT"      },
    { symbol: "HDFCBANK",   yahooSymbol: "HDFCBANK.NS",   name: "HDFC Bank",                 sector: "Banking",   sectorIndex: "^NSEBANK"    },
    { symbol: "INFY",       yahooSymbol: "INFY.NS",       name: "Infosys",                   sector: "IT",        sectorIndex: "^CNXIT"      },
    { symbol: "ICICIBANK",  yahooSymbol: "ICICIBANK.NS",  name: "ICICI Bank",                sector: "Banking",   sectorIndex: "^NSEBANK"    },
    { symbol: "HINDUNILVR", yahooSymbol: "HINDUNILVR.NS", name: "Hindustan Unilever",        sector: "FMCG",      sectorIndex: "^CNXFMCG"    },
    { symbol: "SBIN",       yahooSymbol: "SBIN.NS",       name: "State Bank of India",       sector: "Banking",   sectorIndex: "^NSEBANK"    },
    { symbol: "BHARTIARTL", yahooSymbol: "BHARTIARTL.NS", name: "Bharti Airtel",             sector: "Telecom",   sectorIndex: null           },
    { symbol: "ITC",        yahooSymbol: "ITC.NS",        name: "ITC",                       sector: "FMCG",      sectorIndex: "^CNXFMCG"    },
    { symbol: "KOTAKBANK",  yahooSymbol: "KOTAKBANK.NS",  name: "Kotak Mahindra Bank",       sector: "Banking",   sectorIndex: "^NSEBANK"    },
    { symbol: "LT",         yahooSymbol: "LT.NS",         name: "Larsen & Toubro",           sector: "Infra",     sectorIndex: "^CNXINFRA"   },
    { symbol: "HCLTECH",    yahooSymbol: "HCLTECH.NS",    name: "HCL Technologies",          sector: "IT",        sectorIndex: "^CNXIT"      },
    { symbol: "AXISBANK",   yahooSymbol: "AXISBANK.NS",   name: "Axis Bank",                 sector: "Banking",   sectorIndex: "^NSEBANK"    },
    { symbol: "ASIANPAINT", yahooSymbol: "ASIANPAINT.NS", name: "Asian Paints",              sector: "Consumer",  sectorIndex: "^CNXFMCG"    },
    { symbol: "MARUTI",     yahooSymbol: "MARUTI.NS",     name: "Maruti Suzuki",             sector: "Auto",      sectorIndex: "^CNXAUTO"    },
    { symbol: "SUNPHARMA",  yahooSymbol: "SUNPHARMA.NS",  name: "Sun Pharmaceutical",        sector: "Pharma",    sectorIndex: "^CNXPHARMA"  },
    { symbol: "TITAN",      yahooSymbol: "TITAN.NS",      name: "Titan Company",             sector: "Consumer",  sectorIndex: "^CNXFMCG"    },
    { symbol: "BAJFINANCE", yahooSymbol: "BAJFINANCE.NS", name: "Bajaj Finance",             sector: "Banking",   sectorIndex: "^NSEBANK"    },
    { symbol: "DMART",      yahooSymbol: "DMART.NS",      name: "Avenue Supermarts",         sector: "Retail",    sectorIndex: "^CNXFMCG"    },
    { symbol: "WIPRO",      yahooSymbol: "WIPRO.NS",      name: "Wipro",                     sector: "IT",        sectorIndex: "^CNXIT"      },
    { symbol: "ULTRACEMCO", yahooSymbol: "ULTRACEMCO.NS", name: "UltraTech Cement",          sector: "Infra",     sectorIndex: "^CNXINFRA"   },
    { symbol: "ONGC",       yahooSymbol: "ONGC.NS",       name: "Oil & Natural Gas Corp",    sector: "Energy",    sectorIndex: "^CNXENERGY"  },
    { symbol: "NTPC",       yahooSymbol: "NTPC.NS",       name: "NTPC",                      sector: "Energy",    sectorIndex: "^CNXENERGY"  },
    { symbol: "TATAMOTORS", yahooSymbol: "TATAMOTORS.NS", name: "Tata Motors",               sector: "Auto",      sectorIndex: "^CNXAUTO"    },
    { symbol: "TATASTEEL",  yahooSymbol: "TATASTEEL.NS",  name: "Tata Steel",                sector: "Metal",     sectorIndex: "^CNXMETAL"   },
    { symbol: "POWERGRID",  yahooSymbol: "POWERGRID.NS",  name: "Power Grid Corp",           sector: "Energy",    sectorIndex: "^CNXENERGY"  },
    { symbol: "M&M",        yahooSymbol: "M&M.NS",        name: "Mahindra & Mahindra",       sector: "Auto",      sectorIndex: "^CNXAUTO"    },
    { symbol: "JSWSTEEL",   yahooSymbol: "JSWSTEEL.NS",   name: "JSW Steel",                 sector: "Metal",     sectorIndex: "^CNXMETAL"   },
    { symbol: "ADANIENT",   yahooSymbol: "ADANIENT.NS",   name: "Adani Enterprises",         sector: "Infra",     sectorIndex: "^CNXINFRA"   },
    { symbol: "ADANIPORTS", yahooSymbol: "ADANIPORTS.NS", name: "Adani Ports",               sector: "Infra",     sectorIndex: "^CNXINFRA"   },
    { symbol: "TECHM",      yahooSymbol: "TECHM.NS",      name: "Tech Mahindra",             sector: "IT",        sectorIndex: "^CNXIT"      },
    { symbol: "HDFCLIFE",   yahooSymbol: "HDFCLIFE.NS",   name: "HDFC Life Insurance",       sector: "Banking",   sectorIndex: "^NSEBANK"    },
    { symbol: "BAJAJFINSV", yahooSymbol: "BAJAJFINSV.NS", name: "Bajaj Finserv",             sector: "Banking",   sectorIndex: "^NSEBANK"    },
    { symbol: "SBILIFE",    yahooSymbol: "SBILIFE.NS",    name: "SBI Life Insurance",        sector: "Banking",   sectorIndex: "^NSEBANK"    },
    { symbol: "GRASIM",     yahooSymbol: "GRASIM.NS",     name: "Grasim Industries",         sector: "Infra",     sectorIndex: "^CNXINFRA"   },
    { symbol: "DIVISLAB",   yahooSymbol: "DIVISLAB.NS",   name: "Divi's Laboratories",       sector: "Pharma",    sectorIndex: "^CNXPHARMA"  },
    { symbol: "DRREDDY",    yahooSymbol: "DRREDDY.NS",    name: "Dr. Reddy's Labs",          sector: "Pharma",    sectorIndex: "^CNXPHARMA"  },
    { symbol: "CIPLA",      yahooSymbol: "CIPLA.NS",      name: "Cipla",                     sector: "Pharma",    sectorIndex: "^CNXPHARMA"  },
    { symbol: "EICHERMOT",  yahooSymbol: "EICHERMOT.NS",  name: "Eicher Motors",             sector: "Auto",      sectorIndex: "^CNXAUTO"    },
    { symbol: "APOLLOHOSP", yahooSymbol: "APOLLOHOSP.NS", name: "Apollo Hospitals",          sector: "Pharma",    sectorIndex: "^CNXPHARMA"  },
    { symbol: "COALINDIA",  yahooSymbol: "COALINDIA.NS",  name: "Coal India",                sector: "Energy",    sectorIndex: "^CNXENERGY"  },
    { symbol: "BPCL",       yahooSymbol: "BPCL.NS",       name: "Bharat Petroleum",          sector: "Energy",    sectorIndex: "^CNXENERGY"  },
    { symbol: "BRITANNIA",  yahooSymbol: "BRITANNIA.NS",  name: "Britannia Industries",      sector: "FMCG",      sectorIndex: "^CNXFMCG"    },
    { symbol: "NESTLEIND",  yahooSymbol: "NESTLEIND.NS",  name: "Nestle India",              sector: "FMCG",      sectorIndex: "^CNXFMCG"    },
    { symbol: "TATACONSUM", yahooSymbol: "TATACONSUM.NS", name: "Tata Consumer Products",    sector: "FMCG",      sectorIndex: "^CNXFMCG"    },
    { symbol: "HEROMOTOCO", yahooSymbol: "HEROMOTOCO.NS", name: "Hero MotoCorp",             sector: "Auto",      sectorIndex: "^CNXAUTO"    },
    { symbol: "INDUSINDBK", yahooSymbol: "INDUSINDBK.NS", name: "IndusInd Bank",             sector: "Banking",   sectorIndex: "^NSEBANK"    },
    { symbol: "HINDALCO",   yahooSymbol: "HINDALCO.NS",   name: "Hindalco Industries",       sector: "Metal",     sectorIndex: "^CNXMETAL"   },
    { symbol: "UPL",        yahooSymbol: "UPL.NS",        name: "UPL",                       sector: "Chemicals", sectorIndex: "^CNXPHARMA"  },
    { symbol: "ICICIGI",    yahooSymbol: "ICICIGI.NS",    name: "ICICI Lombard",             sector: "Banking",   sectorIndex: "^NSEBANK"    },
];

const STOCK_MAP = new Map(STOCKS.map((s) => [s.symbol, s]));

export { STOCKS, STOCK_MAP };
