const STOCKS = [
    { symbol: "IDEA",          yahooSymbol: "IDEA.NS",             name: "Vodafone Idea",                           sector: "Telecom",           sectorIndex: null },
    { symbol: "YESBANK",       yahooSymbol: "YESBANK.NS",          name: "Yes Bank",                                sector: "Banking",           sectorIndex: "^NSEBANK" },
    { symbol: "OLAELEC",       yahooSymbol: "OLAELEC.NS",          name: "Ola Electric Mobility",                   sector: "Automobile",        sectorIndex: "^CNXAUTO" },
    { symbol: "PATELENG",      yahooSymbol: "PATELENG.NS",         name: "Patel Engineering",                       sector: "Construction",      sectorIndex: "^CNXINFRA" },
    { symbol: "HCC",           yahooSymbol: "HCC.NS",              name: "Hindustan Construction Company",          sector: "Construction",      sectorIndex: "^CNXINFRA" },
    { symbol: "JPPOWER",       yahooSymbol: "JPPOWER.NS",          name: "Jaiprakash Power Ventures",               sector: "Power",             sectorIndex: "^CNXENERGY" },
    { symbol: "TRIDENT",       yahooSymbol: "TRIDENT.NS",          name: "Trident Limited",                         sector: "Textiles",          sectorIndex: null },
    { symbol: "BHARATCOAL",    yahooSymbol: "BHARATCOAL.NS",       name: "BharatCoal",                              sector: "Unknown",           sectorIndex: null },
    { symbol: "RPOWER",        yahooSymbol: "RPOWER.NS",           name: "Reliance Power",                          sector: "Power",             sectorIndex: "^CNXENERGY" },
    { symbol: "CCAVENUE",      yahooSymbol: "CCAVENUE.NS",         name: "Avenues (CCAvenue)",                      sector: "Fintech",           sectorIndex: "^NSEBANK" },
    { symbol: "SALASAR",       yahooSymbol: "SALASAR.NS",          name: "Salasar Techno Engineering",              sector: "Engineering",       sectorIndex: "^CNXINFRA" },
    { symbol: "SANSTAR",       yahooSymbol: "SANSTAR.NS",          name: "Sanstar Limited",                         sector: "Agro Processing",   sectorIndex: "^CNXFMCG" },
    { symbol: "KPRMILL",       yahooSymbol: "KPRMILL.NS",          name: "KPR Mill",                                sector: "Textiles",          sectorIndex: null },
    { symbol: "SIS",           yahooSymbol: "SIS.NS",              name: "SIS Limited",                             sector: "Services",          sectorIndex: null },
    { symbol: "ROTO",          yahooSymbol: "ROTO.NS",             name: "Roto Pumps",                              sector: "Industrial Equipment", sectorIndex: "^CNXINFRA" },
    { symbol: "EXIDEIND",      yahooSymbol: "EXIDEIND.NS",         name: "Exide Industries",                        sector: "Auto Components",   sectorIndex: "^CNXAUTO" },
    { symbol: "IRFC",          yahooSymbol: "IRFC.NS",             name: "Indian Railway Finance Corporation",      sector: "Financial Services", sectorIndex: "^NSEBANK" },
    { symbol: "ABCAPITAL",     yahooSymbol: "ABCAPITAL.NS",        name: "Aditya Birla Capital",                    sector: "Financial Services", sectorIndex: "^NSEBANK" },
    { symbol: "PINELABS",      yahooSymbol: "PINELABS.NS",         name: "Pine Labs",                               sector: "Fintech",           sectorIndex: "^NSEBANK" },
    { symbol: "FIRSTCRY",      yahooSymbol: "FIRSTCRY.NS",         name: "FirstCry",                                sector: "E-commerce",        sectorIndex: null },
    { symbol: "WIPRO",         yahooSymbol: "WIPRO.NS",            name: "Wipro",                                   sector: "IT Services",       sectorIndex: "^CNXIT" },
    { symbol: "TATASTEEL",     yahooSymbol: "TATASTEEL.NS",        name: "Tata Steel",                              sector: "Metals",            sectorIndex: "^CNXMETAL" },
    { symbol: "HDFCBANK",      yahooSymbol: "HDFCBANK.NS",         name: "HDFC Bank",                               sector: "Banking",           sectorIndex: "^NSEBANK" },
    { symbol: "SBIN",          yahooSymbol: "SBIN.NS",             name: "State Bank of India",                     sector: "Banking",           sectorIndex: "^NSEBANK" },
    { symbol: "ICICIBANK",     yahooSymbol: "ICICIBANK.NS",        name: "ICICI Bank",                              sector: "Banking",           sectorIndex: "^NSEBANK" },
    { symbol: "INFY",          yahooSymbol: "INFY.NS",             name: "Infosys",                                 sector: "IT Services",       sectorIndex: "^CNXIT" },
    { symbol: "ETERNAL",       yahooSymbol: "ETERNAL.NS",          name: "Eternal (Zomato)",                        sector: "Internet",          sectorIndex: null },
    { symbol: "VEDL",          yahooSymbol: "VEDL.NS",             name: "Vedanta Limited",                         sector: "Metals & Mining",   sectorIndex: "^CNXMETAL" },
    { symbol: "IOC",           yahooSymbol: "IOC.NS",              name: "Indian Oil Corporation",                  sector: "Oil & Gas",         sectorIndex: "^CNXENERGY" },
    { symbol: "ADANIPOWER",    yahooSymbol: "ADANIPOWER.NS",       name: "Adani Power",                             sector: "Power",             sectorIndex: "^CNXENERGY" },
    { symbol: "CANBK",         yahooSymbol: "CANBK.NS",            name: "Canara Bank",                             sector: "Banking",           sectorIndex: "^NSEBANK" },
    { symbol: "PNB",           yahooSymbol: "PNB.NS",              name: "Punjab National Bank",                    sector: "Banking",           sectorIndex: "^NSEBANK" },
    { symbol: "UNIONBANK",     yahooSymbol: "UNIONBANK.NS",        name: "Union Bank of India",                     sector: "Banking",           sectorIndex: "^NSEBANK" },
    { symbol: "NTPC",          yahooSymbol: "NTPC.NS",             name: "NTPC Limited",                            sector: "Power",             sectorIndex: "^CNXENERGY" },
    { symbol: "KOTAKBANK",     yahooSymbol: "KOTAKBANK.NS",        name: "Kotak Mahindra Bank",                     sector: "Banking",           sectorIndex: "^NSEBANK" },
    { symbol: "RELIANCE",      yahooSymbol: "RELIANCE.NS",         name: "Reliance Industries",                     sector: "Energy",            sectorIndex: "^CNXENERGY" },
    { symbol: "MOTHERSON",     yahooSymbol: "MOTHERSON.NS",        name: "Samvardhana Motherson International",     sector: "Auto Components",   sectorIndex: "^CNXAUTO" },
    { symbol: "TMCV",          yahooSymbol: "TMCV.NS",             name: "Tata Motors Commercial Vehicles",         sector: "Automobile",        sectorIndex: "^CNXAUTO" },
    { symbol: "TMPV",          yahooSymbol: "TMPV.NS",             name: "Tata Motors Passenger Vehicles",          sector: "Automobile",        sectorIndex: "^CNXAUTO" },
    { symbol: "AXISBANK",      yahooSymbol: "AXISBANK.NS",         name: "Axis Bank",                               sector: "Banking",           sectorIndex: "^NSEBANK" },
    { symbol: "CREDITACC",     yahooSymbol: "CREDITACC.NS",        name: "CreditAccess Grameen",                    sector: "Microfinance",      sectorIndex: "^NSEBANK" },
    { symbol: "JYOTICNC",      yahooSymbol: "JYOTICNC.NS",         name: "Jyoti CNC Automation",                    sector: "Capital Goods",     sectorIndex: "^CNXINFRA" },
    { symbol: "RAMCOCEM",      yahooSymbol: "RAMCOCEM.NS",         name: "The Ramco Cements",                       sector: "Cement",            sectorIndex: "^CNXINFRA" },
    { symbol: "BRIGADE",       yahooSymbol: "BRIGADE.NS",          name: "Brigade Enterprises",                     sector: "Real Estate",       sectorIndex: null },
    { symbol: "HSCL",          yahooSymbol: "HSCL.NS",             name: "HSCL",                                    sector: "Unknown",           sectorIndex: null },
    { symbol: "JSWCEMENT",     yahooSymbol: "JSWCEMENT.NS",        name: "JSW Cement",                              sector: "Cement",            sectorIndex: "^CNXINFRA" },
    { symbol: "CUB",           yahooSymbol: "CUB.NS",              name: "City Union Bank",                         sector: "Banking",           sectorIndex: "^NSEBANK" },
    { symbol: "PNBHOUSING",    yahooSymbol: "PNBHOUSING.NS",       name: "PNB Housing Finance",                     sector: "Housing Finance",   sectorIndex: "^NSEBANK" },
    { symbol: "BANDHANBNK",    yahooSymbol: "BANDHANBNK.NS",       name: "Bandhan Bank",                            sector: "Banking",           sectorIndex: "^NSEBANK" },
    { symbol: "ZENSARTECH",    yahooSymbol: "ZENSARTECH.NS",       name: "Zensar Technologies",                     sector: "IT Services",       sectorIndex: "^CNXIT" },
    { symbol: "UTKARSHBNK",    yahooSymbol: "UTKARSHBNK.NS",       name: "Utkarsh Small Finance Bank",              sector: "Banking",           sectorIndex: "^NSEBANK" },
    { symbol: "SOUTHBANK",     yahooSymbol: "SOUTHBANK.NS",        name: "South Indian Bank",                       sector: "Banking",           sectorIndex: "^NSEBANK" },
    { symbol: "FCL",           yahooSymbol: "FCL.NS",              name: "FCL",                                     sector: "Unknown",           sectorIndex: null },
    { symbol: "RTNPOWER",      yahooSymbol: "RTNPOWER.NS",         name: "RattanIndia Power",                       sector: "Power",             sectorIndex: "^CNXENERGY" },
    { symbol: "ALOKINDS",      yahooSymbol: "ALOKINDS.NS",         name: "Alok Industries",                         sector: "Textiles",          sectorIndex: null },
    { symbol: "MSUMI",         yahooSymbol: "MSUMI.NS",            name: "Motherson Sumi Wiring India",             sector: "Auto Components",   sectorIndex: "^CNXAUTO" },
    { symbol: "SAGILITY",      yahooSymbol: "SAGILITY.NS",         name: "Sagility India",                          sector: "Healthcare Services", sectorIndex: "^CNXPHARMA" },
    { symbol: "IMAGICAA",      yahooSymbol: "IMAGICAA.NS",         name: "Imagicaa World Entertainment",            sector: "Entertainment",     sectorIndex: null },
    { symbol: "ABINFRA",       yahooSymbol: "ABINFRA.NS",          name: "ABInfra",                                 sector: "Unknown",           sectorIndex: null },
    { symbol: "PCJEWELLER",    yahooSymbol: "PCJEWELLER.NS",       name: "PC Jeweller",                             sector: "Retail",            sectorIndex: "^CNXFMCG" },
    { symbol: "IFCI",          yahooSymbol: "IFCI.NS",             name: "IFCI Limited",                            sector: "Financial Services", sectorIndex: "^NSEBANK" },
    { symbol: "SUZLON",        yahooSymbol: "SUZLON.NS",           name: "Suzlon Energy",                           sector: "Renewable Energy",  sectorIndex: "^CNXENERGY" },
    { symbol: "NATIONALUM",    yahooSymbol: "NATIONALUM.NS",       name: "National Aluminium Company",              sector: "Metals",            sectorIndex: "^CNXMETAL" },
    { symbol: "ONGC",          yahooSymbol: "ONGC.NS",             name: "Oil and Natural Gas Corporation",         sector: "Oil & Gas",         sectorIndex: "^CNXENERGY" },
    { symbol: "BEL",           yahooSymbol: "BEL.NS",              name: "Bharat Electronics",                      sector: "Defence",           sectorIndex: "^CNXINFRA" },
    { symbol: "APOLLO",        yahooSymbol: "APOLLO.NS",           name: "Apollo Tyres",                            sector: "Auto Components",   sectorIndex: "^CNXAUTO" },
    { symbol: "IDFCFIRSTB",    yahooSymbol: "IDFCFIRSTB.NS",       name: "IDFC First Bank",                         sector: "Banking",           sectorIndex: "^NSEBANK" },
    { symbol: "MRPL",          yahooSymbol: "MRPL.NS",             name: "Mangalore Refinery and Petrochemicals",   sector: "Oil & Gas",         sectorIndex: "^CNXENERGY" },
    { symbol: "ASHOKLEY",      yahooSymbol: "ASHOKLEY.NS",         name: "Ashok Leyland",                           sector: "Automobile",        sectorIndex: "^CNXAUTO" },
    { symbol: "TATAPOWER",     yahooSymbol: "TATAPOWER.NS",        name: "Tata Power",                              sector: "Power",             sectorIndex: "^CNXENERGY" },
    { symbol: "MAZDOCK",       yahooSymbol: "MAZDOCK.NS",          name: "Mazagon Dock Shipbuilders",               sector: "Defence",           sectorIndex: "^CNXINFRA" },
    { symbol: "OLECTRA",       yahooSymbol: "OLECTRA.NS",          name: "Olectra Greentech",                       sector: "Electric Vehicles", sectorIndex: "^CNXAUTO" },
    { symbol: "KALYANKJIL",    yahooSymbol: "KALYANKJIL.NS",       name: "Kalyan Jewellers India",                  sector: "Retail",            sectorIndex: "^CNXFMCG" },
    { symbol: "JBMA",          yahooSymbol: "JBMA.NS",             name: "JBM Auto",                                sector: "Auto Components",   sectorIndex: "^CNXAUTO" },
    { symbol: "COALINDIA",     yahooSymbol: "COALINDIA.NS",        name: "Coal India",                              sector: "Mining",            sectorIndex: "^CNXMETAL" },
    { symbol: "M&M",           yahooSymbol: "M&M.NS",              name: "Mahindra & Mahindra",                     sector: "Automobile",        sectorIndex: "^CNXAUTO" },
    { symbol: "GODREJIND",     yahooSymbol: "GODREJIND.NS",        name: "Godrej Industries",                       sector: "Diversified",       sectorIndex: null },
    { symbol: "ZEEL",          yahooSymbol: "ZEEL.NS",             name: "Zee Entertainment Enterprises",           sector: "Media",             sectorIndex: null },
    { symbol: "DELHIVERY",     yahooSymbol: "DELHIVERY.NS",        name: "Delhivery",                               sector: "Logistics",         sectorIndex: null },
    { symbol: "KRBL",          yahooSymbol: "KRBL.NS",             name: "KRBL Limited",                            sector: "FMCG",              sectorIndex: "^CNXFMCG" },
    { symbol: "GREENPANEL",    yahooSymbol: "GREENPANEL.NS",       name: "Greenpanel Industries",                   sector: "Building Materials", sectorIndex: "^CNXINFRA" },
    { symbol: "PGIL",          yahooSymbol: "PGIL.NS",             name: "Pearl Global Industries",                 sector: "Textiles",          sectorIndex: null },
    { symbol: "ICIL",          yahooSymbol: "ICIL.NS",             name: "Indo Count Industries",                   sector: "Textiles",          sectorIndex: null },
    { symbol: "MEESHO",        yahooSymbol: "MEESHO.NS",           name: "Meesho",                                  sector: "E-commerce",        sectorIndex: null },
    { symbol: "SBC",           yahooSymbol: "SBC.NS",              name: "SBC",                                     sector: "Unknown",           sectorIndex: null },
    { symbol: "AHCL",          yahooSymbol: "AHCL.NS",             name: "AHCL",                                    sector: "Unknown",           sectorIndex: null },
    { symbol: "PPLPHARMA",     yahooSymbol: "PPLPHARMA.NS",        name: "Piramal Pharma",                          sector: "Pharmaceuticals",   sectorIndex: "^CNXPHARMA" },
    { symbol: "CUPID",         yahooSymbol: "CUPID.NS",            name: "Cupid Limited",                           sector: "Healthcare",        sectorIndex: "^CNXPHARMA" },
    { symbol: "REDINGTON",     yahooSymbol: "REDINGTON.NS",        name: "Redington Limited",                       sector: "IT Distribution",   sectorIndex: "^CNXIT" },
    { symbol: "NAVINFLUOR",    yahooSymbol: "NAVINFLUOR.NS",       name: "Navin Fluorine International",            sector: "Specialty Chemicals", sectorIndex: "^CNXPHARMA" },
    { symbol: "BAJAJ-AUTO",    yahooSymbol: "BAJAJ-AUTO.NS",       name: "Bajaj Auto",                              sector: "Automobile",        sectorIndex: "^CNXAUTO" },
    { symbol: "CHOLAHLDNG",    yahooSymbol: "CHOLAHLDNG.NS",       name: "Cholamandalam Financial Holdings",        sector: "Financial Services", sectorIndex: "^NSEBANK" },
    { symbol: "SHRIRAMFIN",    yahooSymbol: "SHRIRAMFIN.NS",       name: "Shriram Finance",                         sector: "NBFC",              sectorIndex: "^NSEBANK" },
    { symbol: "BSE",           yahooSymbol: "BSE.NS",              name: "BSE Limited",                             sector: "Financial Services", sectorIndex: "^NSEBANK" },
    { symbol: "MTARTECH",      yahooSymbol: "MTARTECH.NS",         name: "MTAR Technologies",                       sector: "Defence",           sectorIndex: "^CNXINFRA" },
    { symbol: "KIRLOSENG",     yahooSymbol: "KIRLOSENG.NS",        name: "Kirloskar Oil Engines",                   sector: "Industrial",        sectorIndex: "^CNXINFRA" },
    { symbol: "STEELCAST",     yahooSymbol: "STEELCAST.NS",        name: "Steelcast Limited",                       sector: "Metals",            sectorIndex: "^CNXMETAL" },
    { symbol: "RAMSYSCORP",    yahooSymbol: "RAMSYSCORP.NS",       name: "RamSysCorp",                              sector: "Unknown",           sectorIndex: null },
    { symbol: "TCS",           yahooSymbol: "TCS.NS",              name: "Tata Consultancy Services",               sector: "IT Services",       sectorIndex: "^CNXIT" },
    { symbol: "LT",            yahooSymbol: "LT.NS",               name: "Larsen & Toubro",                         sector: "Construction",      sectorIndex: "^CNXINFRA" },
    { symbol: "BANKBARODA",    yahooSymbol: "BANKBARODA.NS",       name: "Bank of Baroda",                          sector: "Banking",           sectorIndex: "^NSEBANK" },
    { symbol: "IOB",           yahooSymbol: "IOB.NS",              name: "Indian Overseas Bank",                    sector: "Banking",           sectorIndex: "^NSEBANK" },
    { symbol: "CENTRALBK",     yahooSymbol: "CENTRALBK.NS",        name: "Central Bank of India",                   sector: "Banking",           sectorIndex: "^NSEBANK" },
    { symbol: "MAHABANK",      yahooSymbol: "MAHABANK.NS",         name: "Bank of Maharashtra",                     sector: "Banking",           sectorIndex: "^NSEBANK" },
    { symbol: "UCOBANK",       yahooSymbol: "UCOBANK.NS",          name: "UCO Bank",                                sector: "Banking",           sectorIndex: "^NSEBANK" },
    { symbol: "BANKINDIA",     yahooSymbol: "BANKINDIA.NS",        name: "Bank of India",                           sector: "Banking",           sectorIndex: "^NSEBANK" },
    { symbol: "POWERGRID",     yahooSymbol: "POWERGRID.NS",        name: "Power Grid Corporation of India",         sector: "Power",             sectorIndex: "^CNXENERGY" },
    { symbol: "ADANIGREEN",    yahooSymbol: "ADANIGREEN.NS",       name: "Adani Green Energy",                      sector: "Renewable Energy",  sectorIndex: "^CNXENERGY" },
    { symbol: "ADANIPORTS",    yahooSymbol: "ADANIPORTS.NS",       name: "Adani Ports and SEZ",                     sector: "Infrastructure",    sectorIndex: "^CNXINFRA" },
    { symbol: "SJVN",          yahooSymbol: "SJVN.NS",             name: "SJVN Limited",                            sector: "Power",             sectorIndex: "^CNXENERGY" },
    { symbol: "NHPC",          yahooSymbol: "NHPC.NS",             name: "NHPC Limited",                            sector: "Power",             sectorIndex: "^CNXENERGY" },
    { symbol: "RECLTD",        yahooSymbol: "RECLTD.NS",           name: "REC Limited",                             sector: "Financial Services", sectorIndex: "^NSEBANK" },
    { symbol: "PFC",           yahooSymbol: "PFC.NS",              name: "Power Finance Corporation",               sector: "Financial Services", sectorIndex: "^NSEBANK" },
    { symbol: "IREDA",         yahooSymbol: "IREDA.NS",            name: "Indian Renewable Energy Development Agency", sector: "Financial Services", sectorIndex: "^NSEBANK" },
    { symbol: "JPASSOCIAT",    yahooSymbol: "JPASSOCIAT.NS",       name: "Jaiprakash Associates",                   sector: "Diversified",       sectorIndex: null },
    { symbol: "GTLINFRA",      yahooSymbol: "GTLINFRA.NS",         name: "GTL Infrastructure",                      sector: "Telecom Infrastructure", sectorIndex: null },
    { symbol: "UNITECH",       yahooSymbol: "UNITECH.NS",          name: "Unitech Limited",                         sector: "Real Estate",       sectorIndex: null },
    { symbol: "DISHTV",        yahooSymbol: "DISHTV.NS",           name: "Dish TV India",                           sector: "Media",             sectorIndex: null },
    { symbol: "HMT",           yahooSymbol: "HMT.NS",              name: "HMT Limited",                             sector: "Capital Goods",     sectorIndex: "^CNXINFRA" },
    { symbol: "JSWSTEEL",      yahooSymbol: "JSWSTEEL.NS",         name: "JSW Steel",                               sector: "Metals",            sectorIndex: "^CNXMETAL" },
    { symbol: "HINDALCO",      yahooSymbol: "HINDALCO.NS",         name: "Hindalco Industries",                     sector: "Metals",            sectorIndex: "^CNXMETAL" },
    { symbol: "HINDCOPPER",    yahooSymbol: "HINDCOPPER.NS",       name: "Hindustan Copper",                        sector: "Metals",            sectorIndex: "^CNXMETAL" },
    { symbol: "NMDC",          yahooSymbol: "NMDC.NS",             name: "NMDC Limited",                            sector: "Mining",            sectorIndex: "^CNXMETAL" },
    { symbol: "MOIL",          yahooSymbol: "MOIL.NS",             name: "MOIL Limited",                            sector: "Mining",            sectorIndex: "^CNXMETAL" },
    { symbol: "BPCL",          yahooSymbol: "BPCL.NS",             name: "Bharat Petroleum Corporation",            sector: "Oil & Gas",         sectorIndex: "^CNXENERGY" },
    { symbol: "HINDPETRO",     yahooSymbol: "HINDPETRO.NS",        name: "Hindustan Petroleum Corporation",         sector: "Oil & Gas",         sectorIndex: "^CNXENERGY" },
    { symbol: "GAIL",          yahooSymbol: "GAIL.NS",             name: "GAIL (India)",                            sector: "Oil & Gas",         sectorIndex: "^CNXENERGY" },
    { symbol: "LTIM",          yahooSymbol: "LTIM.NS",             name: "LTIMindtree",                             sector: "IT Services",       sectorIndex: "^CNXIT" },
    { symbol: "MPHASIS",       yahooSymbol: "MPHASIS.NS",          name: "Mphasis",                                 sector: "IT Services",       sectorIndex: "^CNXIT" },
    { symbol: "COFORGE",       yahooSymbol: "COFORGE.NS",          name: "Coforge",                                 sector: "IT Services",       sectorIndex: "^CNXIT" },
    { symbol: "SHOPSTOP",      yahooSymbol: "SHOPSTOP.NS",         name: "Shoppers Stop",                           sector: "Retail",            sectorIndex: "^CNXFMCG" },
    { symbol: "SANGAMIND",     yahooSymbol: "SANGAMIND.NS",        name: "Sangam India",                            sector: "Textiles",          sectorIndex: null },
    { symbol: "KRISHNAPH",     yahooSymbol: "KRISHNAPH.NS",        name: "Krishana Phoschem",                       sector: "Fertilizers",       sectorIndex: "^CNXPHARMA" },
    { symbol: "AETHER",        yahooSymbol: "AETHER.NS",           name: "Aether Industries",                       sector: "Specialty Chemicals", sectorIndex: "^CNXPHARMA" },
    { symbol: "KAPSTON",       yahooSymbol: "KAPSTON.NS",          name: "Kapston Services",                        sector: "Services",          sectorIndex: null },
    { symbol: "ENTERO",        yahooSymbol: "ENTERO.NS",           name: "Entero Healthcare Solutions",             sector: "Healthcare Distribution", sectorIndex: "^CNXPHARMA" },
    { symbol: "SKMEGG",        yahooSymbol: "SKMEGG.NS",           name: "SKM Egg Products Export",                 sector: "Food Processing",   sectorIndex: "^CNXFMCG" },
    { symbol: "MAFATLAL",      yahooSymbol: "MAFATLAL.NS",         name: "Mafatlal Industries",                     sector: "Textiles",          sectorIndex: null },
    { symbol: "DPABHUSHAN",    yahooSymbol: "DPABHUSHAN.NS",       name: "D P Abhushan",                            sector: "Retail",            sectorIndex: "^CNXFMCG" },
    { symbol: "LUMAX",         yahooSymbol: "LUMAX.NS",            name: "Lumax Auto Technologies",                 sector: "Auto Components",   sectorIndex: "^CNXAUTO" },
    { symbol: "TATACONSUM",    yahooSymbol: "TATACONSUM.NS",       name: "Tata Consumer Products",                  sector: "FMCG",              sectorIndex: "^CNXFMCG" },
    { symbol: "BRITANNIA",     yahooSymbol: "BRITANNIA.NS",        name: "Britannia Industries",                    sector: "FMCG",              sectorIndex: "^CNXFMCG" },
    { symbol: "NESTLEIND",     yahooSymbol: "NESTLEIND.NS",        name: "Nestle India",                            sector: "FMCG",              sectorIndex: "^CNXFMCG" },
    { symbol: "HINDUNILVR",    yahooSymbol: "HINDUNILVR.NS",       name: "Hindustan Unilever",                      sector: "FMCG",              sectorIndex: "^CNXFMCG" },
    { symbol: "ITC",           yahooSymbol: "ITC.NS",              name: "ITC Limited",                             sector: "FMCG",              sectorIndex: "^CNXFMCG" },
    { symbol: "DABUR",         yahooSymbol: "DABUR.NS",            name: "Dabur India",                             sector: "FMCG",              sectorIndex: "^CNXFMCG" },
    { symbol: "MARICO",        yahooSymbol: "MARICO.NS",           name: "Marico Limited",                          sector: "FMCG",              sectorIndex: "^CNXFMCG" },
    { symbol: "COLPAL",        yahooSymbol: "COLPAL.NS",           name: "Colgate-Palmolive India",                 sector: "FMCG",              sectorIndex: "^CNXFMCG" },
    { symbol: "GODREJCP",      yahooSymbol: "GODREJCP.NS",         name: "Godrej Consumer Products",                sector: "FMCG",              sectorIndex: "^CNXFMCG" },
    { symbol: "EMAMILTD",      yahooSymbol: "EMAMILTD.NS",         name: "Emami Limited",                           sector: "FMCG",              sectorIndex: "^CNXFMCG" },
    { symbol: "BAJAJFINSV",    yahooSymbol: "BAJAJFINSV.NS",       name: "Bajaj Finserv",                           sector: "Financial Services", sectorIndex: "^NSEBANK" },
    { symbol: "BAJFINANCE",    yahooSymbol: "BAJFINANCE.NS",       name: "Bajaj Finance",                           sector: "NBFC",              sectorIndex: "^NSEBANK" },
    { symbol: "MUTHOOTFIN",    yahooSymbol: "MUTHOOTFIN.NS",       name: "Muthoot Finance",                         sector: "NBFC",              sectorIndex: "^NSEBANK" },
    { symbol: "MANAPPURAM",    yahooSymbol: "MANAPPURAM.NS",       name: "Manappuram Finance",                      sector: "NBFC",              sectorIndex: "^NSEBANK" },
    { symbol: "CHOLAFIN",      yahooSymbol: "CHOLAFIN.NS",         name: "Cholamandalam Investment and Finance",    sector: "NBFC",              sectorIndex: "^NSEBANK" },
    { symbol: "LICHOUSFIN",    yahooSymbol: "LICHOUSFIN.NS",       name: "LIC Housing Finance",                     sector: "Housing Finance",   sectorIndex: "^NSEBANK" },
    { symbol: "CANFINHOME",    yahooSymbol: "CANFINHOME.NS",       name: "Can Fin Homes",                           sector: "Housing Finance",   sectorIndex: "^NSEBANK" },
    { symbol: "AARTIIND",      yahooSymbol: "AARTIIND.NS",         name: "Aarti Industries",                        sector: "Specialty Chemicals", sectorIndex: "^CNXPHARMA" },
    { symbol: "DEEPAKNITR",    yahooSymbol: "DEEPAKNITR.NS",       name: "Deepak Nitrite",                          sector: "Specialty Chemicals", sectorIndex: "^CNXPHARMA" },
    { symbol: "GNFC",          yahooSymbol: "GNFC.NS",             name: "Gujarat Narmada Valley Fertilizers and Chemicals", sector: "Chemicals",         sectorIndex: "^CNXPHARMA" },
    { symbol: "GSFC",          yahooSymbol: "GSFC.NS",             name: "Gujarat State Fertilizers & Chemicals",   sector: "Fertilizers",       sectorIndex: "^CNXPHARMA" },
    { symbol: "CHAMBLFERT",    yahooSymbol: "CHAMBLFERT.NS",       name: "Chambal Fertilisers and Chemicals",       sector: "Fertilizers",       sectorIndex: "^CNXPHARMA" },
    { symbol: "COROMANDEL",    yahooSymbol: "COROMANDEL.NS",       name: "Coromandel International",                sector: "Fertilizers",       sectorIndex: "^CNXPHARMA" },
    { symbol: "UPL",           yahooSymbol: "UPL.NS",              name: "UPL Limited",                             sector: "Agrochemicals",     sectorIndex: "^CNXPHARMA" },
    { symbol: "PI",            yahooSymbol: "PI.NS",               name: "PI Industries",                           sector: "Agrochemicals",     sectorIndex: "^CNXPHARMA" },
    { symbol: "APOLLOHOSP",    yahooSymbol: "APOLLOHOSP.NS",       name: "Apollo Hospitals Enterprise",             sector: "Healthcare",        sectorIndex: "^CNXPHARMA" },
    { symbol: "FORTIS",        yahooSymbol: "FORTIS.NS",           name: "Fortis Healthcare",                       sector: "Healthcare",        sectorIndex: "^CNXPHARMA" },
    { symbol: "MAXHEALTH",     yahooSymbol: "MAXHEALTH.NS",        name: "Max Healthcare Institute",                sector: "Healthcare",        sectorIndex: "^CNXPHARMA" },
    { symbol: "METROPOLIS",    yahooSymbol: "METROPOLIS.NS",       name: "Metropolis Healthcare",                   sector: "Diagnostics",       sectorIndex: "^CNXPHARMA" },
    { symbol: "LALPATHLAB",    yahooSymbol: "LALPATHLAB.NS",       name: "Dr. Lal PathLabs",                        sector: "Diagnostics",       sectorIndex: "^CNXPHARMA" },
    { symbol: "DRREDDY",       yahooSymbol: "DRREDDY.NS",          name: "Dr. Reddy's Laboratories",                sector: "Pharmaceuticals",   sectorIndex: "^CNXPHARMA" },
    { symbol: "CIPLA",         yahooSymbol: "CIPLA.NS",            name: "Cipla Limited",                           sector: "Pharmaceuticals",   sectorIndex: "^CNXPHARMA" },
    { symbol: "SUNPHARMA",     yahooSymbol: "SUNPHARMA.NS",        name: "Sun Pharmaceutical Industries",           sector: "Pharmaceuticals",   sectorIndex: "^CNXPHARMA" },
    { symbol: "DIVISLAB",      yahooSymbol: "DIVISLAB.NS",         name: "Divi's Laboratories",                     sector: "Pharmaceuticals",   sectorIndex: "^CNXPHARMA" },
    { symbol: "AUROPHARMA",    yahooSymbol: "AUROPHARMA.NS",       name: "Aurobindo Pharma",                        sector: "Pharmaceuticals",   sectorIndex: "^CNXPHARMA" },
    { symbol: "TORNTPHARM",    yahooSymbol: "TORNTPHARM.NS",       name: "Torrent Pharmaceuticals",                 sector: "Pharmaceuticals",   sectorIndex: "^CNXPHARMA" },
    { symbol: "OBEROIRLTY",    yahooSymbol: "OBEROIRLTY.NS",       name: "Oberoi Realty",                           sector: "Real Estate",       sectorIndex: null },
    { symbol: "GODREJPROP",    yahooSymbol: "GODREJPROP.NS",       name: "Godrej Properties",                       sector: "Real Estate",       sectorIndex: null },
    { symbol: "PRESTIGE",      yahooSymbol: "PRESTIGE.NS",         name: "Prestige Estates Projects",               sector: "Real Estate",       sectorIndex: null },
    { symbol: "DLF",           yahooSymbol: "DLF.NS",              name: "DLF Limited",                             sector: "Real Estate",       sectorIndex: null },
    { symbol: "PHOENIXLTD",    yahooSymbol: "PHOENIXLTD.NS",       name: "Phoenix Mills",                           sector: "Real Estate",       sectorIndex: null },
    { symbol: "NAUKRI",        yahooSymbol: "NAUKRI.NS",           name: "Info Edge (India)",                       sector: "Internet",          sectorIndex: null },
    { symbol: "POLICYBZR",     yahooSymbol: "POLICYBZR.NS",        name: "PB Fintech (Policybazaar)",               sector: "Insurtech",         sectorIndex: "^NSEBANK" },
    { symbol: "PAYTM",         yahooSymbol: "PAYTM.NS",            name: "One97 Communications (Paytm)",            sector: "Fintech",           sectorIndex: "^NSEBANK" },
    { symbol: "DMART",         yahooSymbol: "DMART.NS",            name: "Avenue Supermarts (DMart)",               sector: "Retail",            sectorIndex: "^CNXFMCG" },
    { symbol: "TRENT",         yahooSymbol: "TRENT.NS",            name: "Trent Limited",                           sector: "Retail",            sectorIndex: "^CNXFMCG" },
    { symbol: "ABFRL",         yahooSymbol: "ABFRL.NS",            name: "Aditya Birla Fashion and Retail",         sector: "Retail",            sectorIndex: "^CNXFMCG" },
    { symbol: "PAGEIND",       yahooSymbol: "PAGEIND.NS",          name: "Page Industries",                         sector: "Textiles",          sectorIndex: null },
    { symbol: "LAXMIMACH",     yahooSymbol: "LAXMIMACH.NS",        name: "Lakshmi Machine Works",                   sector: "Capital Goods",     sectorIndex: "^CNXINFRA" },
    { symbol: "BHEL",          yahooSymbol: "BHEL.NS",             name: "Bharat Heavy Electricals",                sector: "Capital Goods",     sectorIndex: "^CNXINFRA" },
    { symbol: "BEML",          yahooSymbol: "BEML.NS",             name: "BEML Limited",                            sector: "Capital Goods",     sectorIndex: "^CNXINFRA" },
    { symbol: "TIINDIA",       yahooSymbol: "TIINDIA.NS",          name: "Tube Investments of India",               sector: "Auto Components",   sectorIndex: "^CNXAUTO" },
    { symbol: "SCHAEFFLER",    yahooSymbol: "SCHAEFFLER.NS",       name: "Schaeffler India",                        sector: "Auto Components",   sectorIndex: "^CNXAUTO" },
    { symbol: "SKFINDIA",      yahooSymbol: "SKFINDIA.NS",         name: "SKF India",                               sector: "Industrial",        sectorIndex: "^CNXINFRA" },
    { symbol: "CUMMINSIND",    yahooSymbol: "CUMMINSIND.NS",       name: "Cummins India",                           sector: "Capital Goods",     sectorIndex: "^CNXINFRA" },
    { symbol: "ABB",           yahooSymbol: "ABB.NS",              name: "ABB India",                               sector: "Capital Goods",     sectorIndex: "^CNXINFRA" },
    { symbol: "SIEMENS",       yahooSymbol: "SIEMENS.NS",          name: "Siemens Limited",                         sector: "Capital Goods",     sectorIndex: "^CNXINFRA" },
    { symbol: "HAVELLS",       yahooSymbol: "HAVELLS.NS",          name: "Havells India",                           sector: "Consumer Electricals", sectorIndex: "^CNXFMCG" },
    { symbol: "DIXON",         yahooSymbol: "DIXON.NS",            name: "Dixon Technologies",                      sector: "Electronics Manufacturing", sectorIndex: "^CNXIT" },
    { symbol: "TECHM",         yahooSymbol: "TECHM.NS",            name: "Tech Mahindra",                           sector: "IT Services",       sectorIndex: "^CNXIT" },
];

const STOCK_MAP = new Map(STOCKS.map((s) => [s.symbol, s]));

export { STOCKS, STOCK_MAP };
