export const SYMBOL_METADATA = {
    "NSE:IDEA-EQ": { name: "Vodafone Idea", sector: "Telecom" },
    "NSE:YESBANK-EQ": { name: "Yes Bank", sector: "Banking" },
    "NSE:OLAELEC-EQ": { name: "Ola Electric Mobility", sector: "Automobile" },
    "NSE:PATELENG-EQ": { name: "Patel Engineering", sector: "Construction" },
    "NSE:HCC-EQ": { name: "Hindustan Construction Company", sector: "Construction" },
    "NSE:JPPOWER-EQ": { name: "Jaiprakash Power Ventures", sector: "Power" },
    "NSE:TRIDENT-EQ": { name: "Trident Limited", sector: "Textiles" },
    "NSE:RPOWER-EQ": { name: "Reliance Power", sector: "Power" },
    "NSE:SALASAR-EQ": { name: "Salasar Techno Engineering", sector: "Engineering" },
    "NSE:SANSTAR-EQ": { name: "Sanstar Limited", sector: "Agro Processing" },
    "NSE:KPRMILL-EQ": { name: "KPR Mill", sector: "Textiles" },
    "NSE:SIS-EQ": { name: "SIS Limited", sector: "Services" },
    "NSE:ROTO-EQ": { name: "Roto Pumps", sector: "Industrial Equipment" },
    "NSE:EXIDEIND-EQ": { name: "Exide Industries", sector: "Auto Components" },
    "NSE:IRFC-EQ": { name: "Indian Railway Finance Corporation", sector: "Financial Services" },
    "NSE:ABCAPITAL-EQ": { name: "Aditya Birla Capital", sector: "Financial Services" },
    "NSE:PINELABS-EQ": { name: "Pine Labs", sector: "Fintech" },
    "NSE:FIRSTCRY-EQ": { name: "FirstCry", sector: "E-commerce" },

    "NSE:WIPRO-EQ": { name: "Wipro", sector: "IT Services" },
    "NSE:TATASTEEL-EQ": { name: "Tata Steel", sector: "Metals" },
    "NSE:HDFCBANK-EQ": { name: "HDFC Bank", sector: "Banking" },
    "NSE:SBIN-EQ": { name: "State Bank of India", sector: "Banking" },
    "NSE:ICICIBANK-EQ": { name: "ICICI Bank", sector: "Banking" },
    "NSE:INFY-EQ": { name: "Infosys", sector: "IT Services" },
    "NSE:ETERNAL-EQ": { name: "Eternal (Zomato)", sector: "Internet" },
    "NSE:VEDL-EQ": { name: "Vedanta Limited", sector: "Metals & Mining" },
    "NSE:IOC-EQ": { name: "Indian Oil Corporation", sector: "Oil & Gas" },
    "NSE:ADANIPOWER-EQ": { name: "Adani Power", sector: "Power" },
    "NSE:CANBK-EQ": { name: "Canara Bank", sector: "Banking" },
    "NSE:PNB-EQ": { name: "Punjab National Bank", sector: "Banking" },
    "NSE:UNIONBANK-EQ": { name: "Union Bank of India", sector: "Banking" },
    "NSE:NTPC-EQ": { name: "NTPC Limited", sector: "Power" },
    "NSE:KOTAKBANK-EQ": { name: "Kotak Mahindra Bank", sector: "Banking" },
    "NSE:RELIANCE-EQ": { name: "Reliance Industries", sector: "Energy" },
    "NSE:MOTHERSON-EQ": { name: "Samvardhana Motherson International", sector: "Auto Components" },
    "NSE:TMCV-EQ": { name: "Tata Motors Commercial Vehicles", sector: "Automobile" },
    "NSE:TMPV-EQ": { name: "Tata Motors Passenger Vehicles", sector: "Automobile" },
    "NSE:AXISBANK-EQ": { name: "Axis Bank", sector: "Banking" },
    "NSE:CREDITACC-EQ": { name: "CreditAccess Grameen", sector: "Microfinance" },
    "NSE:JYOTICNC-EQ": { name: "Jyoti CNC Automation", sector: "Capital Goods" },
    "NSE:RAMCOCEM-EQ": { name: "The Ramco Cements", sector: "Cement" },
    "NSE:BRIGADE-EQ": { name: "Brigade Enterprises", sector: "Real Estate" },
    "NSE:JSWCEMENT-EQ": { name: "JSW Cement", sector: "Cement" },
    "NSE:CUB-EQ": { name: "City Union Bank", sector: "Banking" },
    "NSE:PNBHOUSING-EQ": { name: "PNB Housing Finance", sector: "Housing Finance" },
    "NSE:BANDHANBNK-EQ": { name: "Bandhan Bank", sector: "Banking" },
    "NSE:ZENSARTECH-EQ": { name: "Zensar Technologies", sector: "IT Services" },
    "NSE:UTKARSHBNK-EQ": { name: "Utkarsh Small Finance Bank", sector: "Banking" },
    "NSE:SOUTHBANK-EQ": { name: "South Indian Bank", sector: "Banking" },
    "NSE:RTNPOWER-EQ": { name: "RattanIndia Power", sector: "Power" },
    "NSE:ALOKINDS-EQ": { name: "Alok Industries", sector: "Textiles" },
    "NSE:MSUMI-EQ": { name: "Motherson Sumi Wiring India", sector: "Auto Components" },
    "NSE:SAGILITY-EQ": { name: "Sagility India", sector: "Healthcare Services" },
    "NSE:IMAGICAA-EQ": { name: "Imagicaa World Entertainment", sector: "Entertainment" },
    "NSE:PCJEWELLER-EQ": { name: "PC Jeweller", sector: "Retail" },
    "NSE:IFCI-EQ": { name: "IFCI Limited", sector: "Financial Services" },
    "NSE:SUZLON-EQ": { name: "Suzlon Energy", sector: "Renewable Energy" },
    "NSE:NATIONALUM-EQ": { name: "National Aluminium Company", sector: "Metals" },
    "NSE:ONGC-EQ": { name: "Oil and Natural Gas Corporation", sector: "Oil & Gas" },
    "NSE:BEL-EQ": { name: "Bharat Electronics", sector: "Defence" },
    "NSE:APOLLO-EQ": { name: "Apollo Tyres", sector: "Auto Components" },
    "NSE:IDFCFIRSTB-EQ": { name: "IDFC First Bank", sector: "Banking" },
    "NSE:MRPL-EQ": { name: "Mangalore Refinery and Petrochemicals", sector: "Oil & Gas" },
    "NSE:ASHOKLEY-EQ": { name: "Ashok Leyland", sector: "Automobile" },
    "NSE:TATAPOWER-EQ": { name: "Tata Power", sector: "Power" },
    "NSE:MAZDOCK-EQ": { name: "Mazagon Dock Shipbuilders", sector: "Defence" },
    "NSE:OLECTRA-EQ": { name: "Olectra Greentech", sector: "Electric Vehicles" },
    "NSE:KALYANKJIL-EQ": { name: "Kalyan Jewellers India", sector: "Retail" },
    "NSE:JBMA-EQ": { name: "JBM Auto", sector: "Auto Components" },
    "NSE:COALINDIA-EQ": { name: "Coal India", sector: "Mining" },
    "NSE:M&M-EQ": { name: "Mahindra & Mahindra", sector: "Automobile" },
    "NSE:GODREJIND-EQ": { name: "Godrej Industries", sector: "Diversified" },
    "NSE:ZEEL-EQ": { name: "Zee Entertainment Enterprises", sector: "Media" },
    "NSE:DELHIVERY-EQ": { name: "Delhivery", sector: "Logistics" },
    "NSE:KRBL-EQ": { name: "KRBL Limited", sector: "FMCG" },
    "NSE:GREENPANEL-EQ": { name: "Greenpanel Industries", sector: "Building Materials" },
    "NSE:MEESHO-EQ": { name: "Meesho", sector: "E-commerce" },
    "NSE:PPLPHARMA-EQ": { name: "Piramal Pharma", sector: "Pharmaceuticals" },
    "NSE:CUPID-EQ": { name: "Cupid Limited", sector: "Healthcare" },
    "NSE:REDINGTON-EQ": { name: "Redington Limited", sector: "IT Distribution" },
    "NSE:NAVINFLUOR-EQ": { name: "Navin Fluorine International", sector: "Specialty Chemicals" },
    "NSE:BAJAJ-AUTO-EQ": { name: "Bajaj Auto", sector: "Automobile" },
    "NSE:CHOLAHLDNG-EQ": { name: "Cholamandalam Financial Holdings", sector: "Financial Services" },
    "NSE:SHRIRAMFIN-EQ": { name: "Shriram Finance", sector: "NBFC" },
    "NSE:BSE-EQ": { name: "BSE Limited", sector: "Financial Services" },
    "NSE:MTARTECH-EQ": { name: "MTAR Technologies", sector: "Defence" },
    "NSE:KIRLOSENG-EQ": { name: "Kirloskar Oil Engines", sector: "Industrial" },
    "NSE:STEELCAST-EQ": { name: "Steelcast Limited", sector: "Metals" },
    "NSE:TCS-EQ": { name: "Tata Consultancy Services", sector: "IT Services" },
    "NSE:LT-EQ": { name: "Larsen & Toubro", sector: "Construction" },

    "NSE:BANKBARODA-EQ": { name: "Bank of Baroda", sector: "Banking" },
    "NSE:IOB-EQ": { name: "Indian Overseas Bank", sector: "Banking" },
    "NSE:CENTRALBK-EQ": { name: "Central Bank of India", sector: "Banking" },
    "NSE:MAHABANK-EQ": { name: "Bank of Maharashtra", sector: "Banking" },
    "NSE:UCOBANK-EQ": { name: "UCO Bank", sector: "Banking" },
    "NSE:BANKINDIA-EQ": { name: "Bank of India", sector: "Banking" },
    "NSE:POWERGRID-EQ": { name: "Power Grid Corporation of India", sector: "Power" },
    "NSE:ADANIGREEN-EQ": { name: "Adani Green Energy", sector: "Renewable Energy" },
    "NSE:ADANIPORTS-EQ": { name: "Adani Ports and SEZ", sector: "Infrastructure" },
    "NSE:SJVN-EQ": { name: "SJVN Limited", sector: "Power" },
    "NSE:NHPC-EQ": { name: "NHPC Limited", sector: "Power" },
    "NSE:RECLTD-EQ": { name: "REC Limited", sector: "Financial Services" },
    "NSE:PFC-EQ": { name: "Power Finance Corporation", sector: "Financial Services" },
    "NSE:IREDA-EQ": { name: "Indian Renewable Energy Development Agency", sector: "Financial Services" },
    "NSE:JPASSOCIAT-EQ": { name: "Jaiprakash Associates", sector: "Diversified" },
    "NSE:GTLINFRA-EQ": { name: "GTL Infrastructure", sector: "Telecom Infrastructure" },
    "NSE:UNITECH-EQ": { name: "Unitech Limited", sector: "Real Estate" },
    "NSE:DISHTV-EQ": { name: "Dish TV India", sector: "Media" },
    "NSE:HMT-EQ": { name: "HMT Limited", sector: "Capital Goods" },
    "NSE:JSWSTEEL-EQ": { name: "JSW Steel", sector: "Metals" },
    "NSE:HINDALCO-EQ": { name: "Hindalco Industries", sector: "Metals" },
    "NSE:HINDCOPPER-EQ": { name: "Hindustan Copper", sector: "Metals" },
    "NSE:NMDC-EQ": { name: "NMDC Limited", sector: "Mining" },
    "NSE:MOIL-EQ": { name: "MOIL Limited", sector: "Mining" },
    "NSE:BPCL-EQ": { name: "Bharat Petroleum Corporation", sector: "Oil & Gas" },
    "NSE:HINDPETRO-EQ": { name: "Hindustan Petroleum Corporation", sector: "Oil & Gas" },
    "NSE:GAIL-EQ": { name: "GAIL (India)", sector: "Oil & Gas" },
    "NSE:LTIM-EQ": { name: "LTIMindtree", sector: "IT Services" },
    "NSE:MPHASIS-EQ": { name: "Mphasis", sector: "IT Services" },
    "NSE:COFORGE-EQ": { name: "Coforge", sector: "IT Services" },
    "NSE:SANGAMIND-EQ": { name: "Sangam India", sector: "Textiles" },
    "NSE:AETHER-EQ": { name: "Aether Industries", sector: "Specialty Chemicals" },
    "NSE:ENTERO-EQ": { name: "Entero Healthcare Solutions", sector: "Healthcare Distribution" },
    "NSE:SKMEGG-EQ": { name: "SKM Egg Products Export", sector: "Food Processing" },
    "NSE:MAFATLAL-EQ": { name: "Mafatlal Industries", sector: "Textiles" },
    "NSE:DPABHUSHAN-EQ": { name: "D P Abhushan", sector: "Retail" },
    "NSE:LUMAX-EQ": { name: "Lumax Auto Technologies", sector: "Auto Components" },
    "NSE:TATACONSUM-EQ": { name: "Tata Consumer Products", sector: "FMCG" },
    "NSE:BRITANNIA-EQ": { name: "Britannia Industries", sector: "FMCG" },
    "NSE:NESTLEIND-EQ": { name: "Nestle India", sector: "FMCG" },
    "NSE:HINDUNILVR-EQ": { name: "Hindustan Unilever", sector: "FMCG" },
    "NSE:ITC-EQ": { name: "ITC Limited", sector: "FMCG" },
    "NSE:DABUR-EQ": { name: "Dabur India", sector: "FMCG" },
    "NSE:MARICO-EQ": { name: "Marico Limited", sector: "FMCG" },
    "NSE:COLPAL-EQ": { name: "Colgate-Palmolive India", sector: "FMCG" },
    "NSE:GODREJCP-EQ": { name: "Godrej Consumer Products", sector: "FMCG" },
    "NSE:EMAMILTD-EQ": { name: "Emami Limited", sector: "FMCG" },
    "NSE:BAJAJFINSV-EQ": { name: "Bajaj Finserv", sector: "Financial Services" },
    "NSE:BAJFINANCE-EQ": { name: "Bajaj Finance", sector: "NBFC" },
    "NSE:MUTHOOTFIN-EQ": { name: "Muthoot Finance", sector: "NBFC" },
    "NSE:MANAPPURAM-EQ": { name: "Manappuram Finance", sector: "NBFC" },
    "NSE:CHOLAFIN-EQ": { name: "Cholamandalam Investment and Finance", sector: "NBFC" },
    "NSE:LICHOUSFIN-EQ": { name: "LIC Housing Finance", sector: "Housing Finance" },
    "NSE:CANFINHOME-EQ": { name: "Can Fin Homes", sector: "Housing Finance" },
    "NSE:AARTIIND-EQ": { name: "Aarti Industries", sector: "Specialty Chemicals" },
    "NSE:DEEPAKNITR-EQ": { name: "Deepak Nitrite", sector: "Specialty Chemicals" },
    "NSE:GNFC-EQ": { name: "Gujarat Narmada Valley Fertilizers and Chemicals", sector: "Chemicals" },
    "NSE:GSFC-EQ": { name: "Gujarat State Fertilizers & Chemicals", sector: "Fertilizers" },
    "NSE:CHAMBLFERT-EQ": { name: "Chambal Fertilisers and Chemicals", sector: "Fertilizers" },
    "NSE:COROMANDEL-EQ": { name: "Coromandel International", sector: "Fertilizers" },
    "NSE:UPL-EQ": { name: "UPL Limited", sector: "Agrochemicals" },
    "NSE:PI-EQ": { name: "PI Industries", sector: "Agrochemicals" },
    "NSE:APOLLOHOSP-EQ": { name: "Apollo Hospitals Enterprise", sector: "Healthcare" },
    "NSE:FORTIS-EQ": { name: "Fortis Healthcare", sector: "Healthcare" },
    "NSE:MAXHEALTH-EQ": { name: "Max Healthcare Institute", sector: "Healthcare" },
    "NSE:METROPOLIS-EQ": { name: "Metropolis Healthcare", sector: "Diagnostics" },
    "NSE:LALPATHLAB-EQ": { name: "Dr. Lal PathLabs", sector: "Diagnostics" },
    "NSE:DRREDDY-EQ": { name: "Dr. Reddy's Laboratories", sector: "Pharmaceuticals" },
    "NSE:CIPLA-EQ": { name: "Cipla Limited", sector: "Pharmaceuticals" },
    "NSE:SUNPHARMA-EQ": { name: "Sun Pharmaceutical Industries", sector: "Pharmaceuticals" },
    "NSE:DIVISLAB-EQ": { name: "Divi's Laboratories", sector: "Pharmaceuticals" },
    "NSE:AUROPHARMA-EQ": { name: "Aurobindo Pharma", sector: "Pharmaceuticals" },
    "NSE:TORNTPHARM-EQ": { name: "Torrent Pharmaceuticals", sector: "Pharmaceuticals" },
    "NSE:OBEROIRLTY-EQ": { name: "Oberoi Realty", sector: "Real Estate" },
    "NSE:GODREJPROP-EQ": { name: "Godrej Properties", sector: "Real Estate" },
    "NSE:PRESTIGE-EQ": { name: "Prestige Estates Projects", sector: "Real Estate" },
    "NSE:DLF-EQ": { name: "DLF Limited", sector: "Real Estate" },
    "NSE:PHOENIXLTD-EQ": { name: "Phoenix Mills", sector: "Real Estate" },
    "NSE:NAUKRI-EQ": { name: "Info Edge (India)", sector: "Internet" },
    "NSE:POLICYBZR-EQ": { name: "PB Fintech (Policybazaar)", sector: "Insurtech" },
    "NSE:PAYTM-EQ": { name: "One97 Communications (Paytm)", sector: "Fintech" },
    "NSE:DMART-EQ": { name: "Avenue Supermarts (DMart)", sector: "Retail" },
    "NSE:TRENT-EQ": { name: "Trent Limited", sector: "Retail" },
    "NSE:ABFRL-EQ": { name: "Aditya Birla Fashion and Retail", sector: "Retail" },
    "NSE:PAGEIND-EQ": { name: "Page Industries", sector: "Textiles" },
    "NSE:LAXMIMACH-EQ": { name: "Lakshmi Machine Works", sector: "Capital Goods" },
    "NSE:BHEL-EQ": { name: "Bharat Heavy Electricals", sector: "Capital Goods" },
    "NSE:BEML-EQ": { name: "BEML Limited", sector: "Capital Goods" },
    "NSE:TIINDIA-EQ": { name: "Tube Investments of India", sector: "Auto Components" },
    "NSE:SCHAEFFLER-EQ": { name: "Schaeffler India", sector: "Auto Components" },
    "NSE:SKFINDIA-EQ": { name: "SKF India", sector: "Industrial" },
    "NSE:CUMMINSIND-EQ": { name: "Cummins India", sector: "Capital Goods" },
    "NSE:ABB-EQ": { name: "ABB India", sector: "Capital Goods" },
    "NSE:SIEMENS-EQ": { name: "Siemens Limited", sector: "Capital Goods" },
    "NSE:HAVELLS-EQ": { name: "Havells India", sector: "Consumer Electricals" },
    "NSE:DIXON-EQ": { name: "Dixon Technologies", sector: "Electronics Manufacturing" },
    "NSE:TECHM-EQ": { name: "Tech Mahindra", sector: "IT Services" },
};

export function getMetadata(fyersSymbol) {
    return (
        SYMBOL_METADATA[fyersSymbol] ?? {
            name: fyersSymbol.replace(/^(NSE|BSE):/, "").replace(/-EQ$/, ""),
            sector: "Unknown",
        }
    );
}
