package marketdata

import (
	"bufio"
	"encoding/json"
	"os"
	"path/filepath"
	"testing"
)

// Shadow replay parity.
//
// The golden fixtures prove the contract's named cases. This proves the two
// implementations agree over a session's worth of interleaved traffic, where
// latches, velocity windows and volume minutes all interact.
//
// The input and the incumbent's output are generated by
// apps/api/scripts/shadowReplay.js. Point SHADOW_REPLAY_DIR at its output.
//
// Zero divergence is the bar. This is the evidence a cutover needs, and until
// it runs against a real session it is evidence about behaviour, not about the
// venue.

type shadowSetup struct {
	Commitments []Commitment `json:"commitments"`
	Watches     []struct {
		Symbol           string    `json:"symbol"`
		EntryPaise       *int64    `json:"entryPaise"`
		ThesisID         string    `json:"thesisId"`
		CorrelationID    string    `json:"correlationId"`
		Direction        Direction `json:"direction"`
		VwapPaise        *int64    `json:"vwapPaise"`
		VolumeBaseline   *float64  `json:"volumeBaseline"`
		VolumeSpikeRatio *float64  `json:"volumeSpikeRatio"`
	} `json:"watches"`
}

type shadowTick struct {
	Symbol           string `json:"symbol"`
	PricePaise       int64  `json:"pricePaise"`
	ReceiveTs        int64  `json:"receiveTs"`
	CumulativeVolume *int64 `json:"cumulativeVolume"`
}

type shadowState struct {
	Symbol    string `json:"symbol"`
	LastPaise int64  `json:"lastPaise"`
	HighPaise int64  `json:"highPaise"`
	LowPaise  int64  `json:"lowPaise"`
	Sequence  uint64 `json:"sequence"`
	UpdatedTs int64  `json:"updatedTs"`
}

func readJSONL[T any](t *testing.T, path string) []T {
	t.Helper()
	f, err := os.Open(path)
	if err != nil {
		t.Fatalf("opening %s: %v", path, err)
	}
	defer f.Close()

	var out []T
	sc := bufio.NewScanner(f)
	sc.Buffer(make([]byte, 0, 1<<20), 1<<20)
	for sc.Scan() {
		if len(sc.Bytes()) == 0 {
			continue
		}
		var v T
		if err := json.Unmarshal(sc.Bytes(), &v); err != nil {
			t.Fatalf("parsing a line of %s: %v", path, err)
		}
		out = append(out, v)
	}
	if err := sc.Err(); err != nil {
		t.Fatalf("reading %s: %v", path, err)
	}
	return out
}

func readJSON[T any](t *testing.T, path string) T {
	t.Helper()
	raw, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("reading %s: %v", path, err)
	}
	var v T
	if err := json.Unmarshal(raw, &v); err != nil {
		t.Fatalf("parsing %s: %v", path, err)
	}
	return v
}

func TestShadowReplayParity(t *testing.T) {
	dir := os.Getenv("SHADOW_REPLAY_DIR")
	if dir == "" {
		t.Skip("SHADOW_REPLAY_DIR not set; run apps/api/scripts/shadowReplay.js first")
	}

	setup := readJSON[shadowSetup](t, filepath.Join(dir, "setup.json"))
	ticks := readJSONL[shadowTick](t, filepath.Join(dir, "ticks.jsonl"))
	want := readJSONL[MarketEvent](t, filepath.Join(dir, "events.jsonl"))
	wantState := readJSON[[]shadowState](t, filepath.Join(dir, "finalState.json"))

	lane := NewLane()
	for _, c := range setup.Commitments {
		if !lane.Arm(c) {
			t.Fatalf("refused a commitment the incumbent armed: %+v", c)
		}
	}
	for _, w := range setup.Watches {
		lane.Watch(w.Symbol, Watch{
			EntryPaise: w.EntryPaise, ThesisID: w.ThesisID,
			CorrelationID: w.CorrelationID, Direction: w.Direction,
		}, 0)
		if w.VwapPaise != nil {
			lane.UpdateVwap(w.Symbol, *w.VwapPaise)
		}
		if w.VolumeBaseline != nil && w.VolumeSpikeRatio != nil {
			lane.UpdateVolumeBaseline(w.Symbol, *w.VolumeBaseline, *w.VolumeSpikeRatio)
		}
	}

	var got []MarketEvent
	for _, tk := range ticks {
		got = append(got, lane.Observe(NormalisedTick{
			Contract: TickContract, Symbol: tk.Symbol,
			PricePaise: tk.PricePaise, ReceiveTs: tk.ReceiveTs,
			CumulativeVolume: tk.CumulativeVolume,
		})...)
	}

	t.Logf("replayed %d ticks: go produced %d events, node produced %d",
		len(ticks), len(got), len(want))

	if len(got) != len(want) {
		divergence(t, got, want)
		t.Fatalf("event count diverged: go %d, node %d", len(got), len(want))
	}
	diverged := 0
	for i := range got {
		if got[i] != want[i] {
			if diverged < 10 {
				t.Errorf("event %d diverged\n  go:   %+v\n  node: %+v", i, got[i], want[i])
			}
			diverged++
		}
	}
	if diverged > 0 {
		t.Fatalf("%d of %d events diverged", diverged, len(got))
	}

	for _, w := range wantState {
		s := lane.Snapshot(w.Symbol)
		if s == nil {
			t.Fatalf("%s: node observed it, go did not", w.Symbol)
		}
		if s.LastPaise != w.LastPaise || s.HighPaise != w.HighPaise ||
			s.LowPaise != w.LowPaise || s.Sequence != w.Sequence || s.UpdatedTs != w.UpdatedTs {
			t.Errorf("%s final state diverged\n  go:   %+v\n  node: %+v", w.Symbol, *s, w)
		}
	}

	// A replay that produced nothing would pass every assertion above and prove
	// nothing at all.
	byKind := map[Kind]int{}
	for _, e := range got {
		byKind[e.Kind]++
	}
	for _, kind := range []Kind{
		KindStop, KindTarget, KindInvalidation, KindStopApproach,
		KindTargetApproach, KindPriceJump, KindVwapDeviation, KindVolumeSpike,
	} {
		if byKind[kind] == 0 {
			t.Errorf("the replay never exercised %s", kind)
		}
	}
	for k, n := range byKind {
		t.Logf("  %-18s %d", k, n)
	}
}

// The first place the two implementations stop agreeing is the useful one.
func divergence(t *testing.T, got, want []MarketEvent) {
	t.Helper()
	n := len(got)
	if len(want) < n {
		n = len(want)
	}
	for i := 0; i < n; i++ {
		if got[i] != want[i] {
			t.Logf("first divergence at %d\n  go:   %+v\n  node: %+v", i, got[i], want[i])
			return
		}
	}
	t.Logf("agreed on the first %d events, then one side stopped", n)
}

// Same input, same work, both runtimes: the throughput half of the evidence.
func BenchmarkShadowReplay(b *testing.B) {
	dir := os.Getenv("SHADOW_REPLAY_DIR")
	if dir == "" {
		b.Skip("SHADOW_REPLAY_DIR not set")
	}
	t := &testing.T{}
	setup := readJSON[shadowSetup](t, filepath.Join(dir, "setup.json"))
	ticks := readJSONL[shadowTick](t, filepath.Join(dir, "ticks.jsonl"))

	b.ReportAllocs()
	b.ResetTimer()
	for n := 0; n < b.N; n++ {
		b.StopTimer()
		lane := NewLane()
		for _, c := range setup.Commitments {
			lane.Arm(c)
		}
		for _, w := range setup.Watches {
			lane.Watch(w.Symbol, Watch{EntryPaise: w.EntryPaise, ThesisID: w.ThesisID,
				CorrelationID: w.CorrelationID, Direction: w.Direction}, 0)
			if w.VwapPaise != nil {
				lane.UpdateVwap(w.Symbol, *w.VwapPaise)
			}
			if w.VolumeBaseline != nil && w.VolumeSpikeRatio != nil {
				lane.UpdateVolumeBaseline(w.Symbol, *w.VolumeBaseline, *w.VolumeSpikeRatio)
			}
		}
		b.StartTimer()
		for _, tk := range ticks {
			lane.Observe(NormalisedTick{Contract: TickContract, Symbol: tk.Symbol,
				PricePaise: tk.PricePaise, ReceiveTs: tk.ReceiveTs,
				CumulativeVolume: tk.CumulativeVolume})
		}
	}
	b.ReportMetric(float64(len(ticks)), "ticks/op")
}
