import { sha256Hex } from "@zentrade/kernel";
import { chunkKey } from "./identity.js";

/**
 * Chunking (M17) — part of semantics `knowledge_v1`, FROZEN: CHUNK_MAX_CHARS
 * and this algorithm define chunk boundaries, so changing either requires a
 * new semantics id.
 *
 * Chunks are deterministic, contiguous, non-overlapping slices of the
 * normalized document text, addressed by character offsets. Paragraphs (text
 * between blank lines) are the natural unit; consecutive paragraphs pack
 * together up to the budget, and any single paragraph longer than the budget
 * is hard-split at the character boundary so no chunk ever exceeds it.
 *
 * Chunk TEXT is never stored — only offsets and a hash. It is regenerated by
 * slicing the stored normalized text, exactly as narratives regenerate from
 * the journal. Replay recomputes identical offsets, hashes, and keys.
 */

export const CHUNK_MAX_CHARS = 1200;

const PARAGRAPH_SEPARATOR = /\n[ \t]*\n\s*/g;

interface Span {
    start: number;
    end: number;
}

const segmentParagraphs = (text: string): Span[] => {
    const segments: Span[] = [];
    let cursor = 0;
    PARAGRAPH_SEPARATOR.lastIndex = 0;
    let match: RegExpExecArray | null;
    while ((match = PARAGRAPH_SEPARATOR.exec(text)) !== null) {
        if (match.index > cursor) segments.push({ start: cursor, end: match.index });
        cursor = match.index + match[0].length;
    }
    if (cursor < text.length) segments.push({ start: cursor, end: text.length });
    return segments;
};

const packSegments = (segments: readonly Span[], maxChars: number): Span[] => {
    const spans: Span[] = [];
    let current: Span | null = null;
    const flush = () => {
        if (current) {
            spans.push(current);
            current = null;
        }
    };
    for (const seg of segments) {
        if (seg.end - seg.start > maxChars) {
            flush();
            for (let pos = seg.start; pos < seg.end; pos += maxChars) {
                spans.push({ start: pos, end: Math.min(pos + maxChars, seg.end) });
            }
            continue;
        }
        if (current && seg.end - current.start <= maxChars) {
            current.end = seg.end;
        } else {
            flush();
            current = { start: seg.start, end: seg.end };
        }
    }
    flush();
    return spans;
};

export interface BuiltChunk {
    ordinal: number;
    charStart: number;
    charEnd: number;
    text: string;
    textSha256: string;
    chunkKey: string;
}

export const chunkDocument = (
    normalizedText: string,
    docKey: string,
    maxChars: number = CHUNK_MAX_CHARS,
): BuiltChunk[] =>
    packSegments(segmentParagraphs(normalizedText), maxChars).map((span, ordinal) => {
        const text = normalizedText.slice(span.start, span.end);
        const textSha256 = sha256Hex(text);
        return {
            ordinal,
            charStart: span.start,
            charEnd: span.end,
            text,
            textSha256,
            chunkKey: chunkKey(docKey, ordinal, textSha256),
        };
    });
